---
title: "dev_history.Rmd package orgaphoto"
author: "Benjamin Louis"
date: "23/01/2021"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r development, include=FALSE}
library(testthat)
```

<!--
# Description of your package

This will fill the description of your package.
--> 

```{r description, eval=FALSE}
# Describe your package
fusen::fill_description(
  fields = list(
    Title = "Rename and organise your photos",
    Description = "Use helper functions to (smartly?) rename your photo and organise them in your computer.",
    `Authors@R` = c(
      person("Benjamin", "Louis", email = "contact@benjaminlouis-stat.fr", role = c("aut", "cre"))
    )
  )
)
# Define License with use_*_license()
usethis::use_mit_license("Benjamin Louis")
```

# My function

```{r function-1}

```

```{r examples-1}

```

```{r tests-1}
test_that("my_function works properly", {

})
```


```{r development-1, eval=FALSE}
# Run but keep eval=FALSE to avoid infinite loop
# Execute in the console directly
fusen::inflate(
  rmd = "dev/dev_history.Rmd",
  check = FALSE,
  name = "using_orgaphoto"
  )

# Versionning
usethis::use_git()
```

<!-- # Inflate your package -->

<!-- You're one inflate from paper to box. -->
<!-- Build your package from this very Rmd using `fusen::inflate()` -->

<!-- - Verify your `"DESCRIPTION"` file has been updated -->
<!-- - Verify your function is in `"R/"` directory -->
<!-- - Verify your test is in `"tests/testthat/"` directory -->
<!-- - Verify this Rmd appears in `"vignettes/"` directory -->
